USERNAME="gerrit"
USERPASS="gerrit"

# create user and modify password
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$USERNAME";
  ALTER USER "$USERNAME" WITH PASSWORD '$USERPASS';
EOSQL

# create caches DB
DBNAME="gerrit_caches"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$DBNAME" ENCODING UTF8;
  GRANT ALL PRIVILEGES ON DATABASE "$DBNAME" TO "$USERNAME";
EOSQL

# create review DB
DBNAME="gerrit_review"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$DBNAME" ENCODING UTF8;
  GRANT ALL PRIVILEGES ON DATABASE "$DBNAME" TO "$USERNAME";
EOSQL
